# Generated by Django 3.2.14 on 2023-04-01 09:35

import audio_validator.validator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nasheed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('poster', models.ImageField(upload_to='nasheeds/posters', verbose_name='Poster')),
                ('audio', models.FileField(upload_to='nasheeds/audios', validators=[audio_validator.validator.AudioValidator('mp3')], verbose_name='Audio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'nasheed',
                'verbose_name_plural': 'nasheeds',
            },
        ),
    ]
