# Generated by Django 3.2.14 on 2023-08-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nasheeds', '0002_auto_20230808_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasheed',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='nasheed',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Duration'),
        ),
    ]
